# Generated by Django 5.0.3 on 2024-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name': 'Коллекции фото', 'verbose_name_plural': 'Коллекции фото'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='maintitle',
            options={'verbose_name': 'Заголовок сайта', 'verbose_name_plural': 'Заголовок сайта'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервис'},
        ),
        migrations.RemoveField(
            model_name='banners',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='title',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='maintitle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
        migrations.AddField(
            model_name='banners',
            name='description_en',
            field=models.TextField(default='test', verbose_name='Описание на английском'),
        ),
        migrations.AddField(
            model_name='banners',
            name='description_ru',
            field=models.TextField(default='test', verbose_name='Описание на русском'),
        ),
        migrations.AddField(
            model_name='banners',
            name='description_uz',
            field=models.TextField(default='test', verbose_name='Описание на узбекском'),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_en',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на английском'),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_ru',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на русском'),
        ),
        migrations.AddField(
            model_name='banners',
            name='title_uz',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на узбекском'),
        ),
        migrations.AddField(
            model_name='collections',
            name='title_en',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на английском'),
        ),
        migrations.AddField(
            model_name='collections',
            name='title_ru',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на русском'),
        ),
        migrations.AddField(
            model_name='collections',
            name='title_uz',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на узбекском'),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='title_en',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на английском'),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='title_ru',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на русском'),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='title_uz',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на узбекском'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_en',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на английском'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_ru',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на русском'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_uz',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на узбекском'),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(default='test', verbose_name='Описание на английском'),
        ),
        migrations.AddField(
            model_name='services',
            name='description_ru',
            field=models.TextField(default='test', verbose_name='Описание на русском'),
        ),
        migrations.AddField(
            model_name='services',
            name='description_uz',
            field=models.TextField(default='test', verbose_name='Описание на узбекском'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на английском'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на русском'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_uz',
            field=models.CharField(default='test', max_length=256, verbose_name='Слоган на узбекском'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
