# Generated by Django 5.0.3 on 2024-10-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_collections_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Раздел о нас', 'verbose_name_plural': 'Раздел о нас'},
        ),
    ]
