# Generated by Django 5.0.3 on 2024-10-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_banners_about_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='img/projects/', verbose_name='фото'),
        ),
    ]
